# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Set_fact es para setear variables, aqui seteo el nombre de la carpeta que se crea al descargar rtpengine
- set_fact: rtpengine_name=rtpengine-mr5.5.3.1
  tags: kamailio
# Version de kamailio a instalar
- set_fact: kamailio_version=5.1.4
  tags: ['kamailio','postinstall']

# Detecto si existe el binario de rtpengine y registro el resultado en rtpengine_installed
- name: Check if Rtpengine is installed
  command: test -f /usr/local/bin/rtpengine
  register: rtpengine_installed
  tags: kamailio
  become: true
  become_method: sudo
  ignore_errors: yes

# mensaje para mostrar si rtpengine no está instalado
- debug: msg="RTPengine no está instalado, se procede a la instalación"
  when: rtpengine_installed|failed
  tags: kamailio

# mensaje si rtpengine está instalado
- debug: msg="RTPengine ya se encuentra instalado se omite instalación"
  when: rtpengine_installed|succeeded
  tags: kamailio

- include: packages_installation.yml
  tags: kamailio
  when: rtpengine_installed|failed

#  Si rtpengine_installed es failed incluyo la tarea de instalacion. Osea el sistema detecta cuando rtpengine
#  está instalado o no y en caso de que no lo  esté lo instala sino omite
- include: rtpengine_installation.yml
  tags: kamailio
  when: rtpengine_installed|failed

- include: rtpengine_configuration.yml
  tags: kamailio

# Lo mismo se hace con kamailio
- name: Check if Kamailio version is 5.1.4
  shell: "{{ kamailio_location }}/sbin/kamailio -v |head -1 |awk -F \" \" '{print $3}'"
  register: kamailio_installed
  tags: ['kamailio','postinstall']
  become: true
  become_method: sudo
  ignore_errors: yes

- debug: msg="Kamailio 5.1.4 is not installed, proceeding to install"
  tags: ['kamailio','postinstall']
  when: kamailio_installed.stdout != "5.1.4"

- debug: msg="Kamailio is already installed in version 5.1.4, skipping installation steps"
  tags: ['kamailio','postinstall']
  when: kamailio_installed.stdout == "5.1.4"

- name: Uninstall actual kamailio version
  file: state=absent path={{ kamailio_location }}/{{ item }}
  with_items:
    - sbin
    - etc/kamailio
    - lib64
  when: kamailio_installed.stdout != "5.1.4"
  tags: postinstall

- name: Check if Kamailio certificates exists
  shell: test -d {{ kamailio_location }}/etc/certs || test -d /opt/kamailio/etc/certs
  register: certs_exists
  tags: ['kamailio','postinstall']
  become: true
  become_method: sudo
  ignore_errors: yes

- include: kamailio_installation.yml
  tags: ['kamailio','postinstall']
  when: kamailio_installed.stdout != "5.1.4"

- include: certificate_CA.yml
  tags: ['kamailio','postinstall']
  when: certs_exists|failed

- include: kamailio_configuration.yml
  tags: ['kamailio','postinstall']

#  Se pasan los certificados al host
- name: Copy of the certificates from kamailio server to omniapp (cluster)
  fetch: src={{ kamailio_location }}/etc/certs/{{ item.src }} dest=/var/tmp/ansible/{{ item.dest }} flat=yes
  with_items:
    - { src: 'demoCA/cert.pem', dest: 'ca_cert.pem'}
    - { src: 'cert.pem', dest: 'cert.pem' }
    - { src: 'key.pem', dest: 'key.pem' }
  when: cluster != 0
  tags: postinstall

- include: roles/prerequisitos/tasks/reboot.yml
  when: cluster != 0 and ansible_os_family == "RedHat"

- name: Wait for the server to finish rebooting
  become: no
  local_action: wait_for host="{{ kamailio_ip }}" delay=15 state=started port={{ ansible_ssh_port }} timeout=600
  tags: reboot
  when: ansible_os_family == "RedHat" and cluster !=0
