# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Detecto si existe el binario de rtpengine y registro el resultado en rtpengine_installed
- name: Check if Rtpengine is installed
  command: test -f /usr/local/bin/rtpengine
  ignore_errors: True
  register: rtpengine_installed
  tags: rtpengine
  become: true
  become_method: sudo

# mensaje para mostrar si rtpengine no está instalado
- debug: msg="RTPengine no está instalado, se procede a la instalación"
  when: rtpengine_installed|failed
  tags: rtpengine

# mensaje si rtpengine está instalado
- debug: msg="RTPengine ya se encuentra instalado se omite instalación"
  when: rtpengine_installed|succeeded
  tags: rtpengine

#  Si rtpengine_installed es failed incluyo la tarea de instalacion. Osea el sistema detecta cuando rtpengine
#  está instalado o no y en caso de que no lo  esté lo instala sino omite
- include: rtpengine.yml
  tags: rtpengine
  when: rtpengine_installed|failed

# Lo mismo se hace con kamailio
- name: Check if Kamailio is installed
  shell: test -f {{ kamailio_location }}/sbin/kamailio
  ignore_errors: True
  register: kamailio_installed
  tags: kamailio
  become: true
  become_method: sudo

- debug: msg="Kamailio no está instalado, se procede a la instalación"
  tags: kamailio
  when: kamailio_installed|failed

- debug: msg="Kamailio ya se encuentra instalado se omite instalación"
  tags: kamailio
  when: kamailio_installed|succeeded

- name: Check if Kamailio certificates exists
  shell: test -d {{ kamailio_location }}/etc/certs || test -d /opt/kamailio/etc/certs
  ignore_errors: True
  register: certs_exists
  tags: kamailio
  become: true
  become_method: sudo

- include: kamailio.yml
  tags: kamailio
  when: kamailio_installed|failed

- include: postgresusers.yml
  tags: kamailio

- include: certificate_CA.yml
  tags: kamailio
  when: certs_exists|failed

- include: kamailio-as-service.yml
  tags: kamailio
