# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Hay tambien un template del archivo de configuracion de postgresql
# Deuda tecnica -- FIX ME--
# Hay que ver si se puede modificar el archivo despues de creado porque está dejando loguearse a postges sin necesidad de contraseña
- name: Modify of pg_hba.conf file (centos)
  template: src=roles/kamailio/templates/pg_hba.conf.j2 dest=/var/lib/pgsql/9.6/data/pg_hba.conf
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Esto es para debian
- name: Modify of pg_hba.conf file (debian)
  template: src=roles/kamailio/templates/pg_hba.conf.j2 dest=/etc/postgresql/9.6/main/pg_hba.conf
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

# Restarteamos servicio
- name: Restart postgres service (centos)
  service: name=postgresql-9.6 state=restarted enabled=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Restart postgres service (debian)
  service: name=postgresql state=restarted enabled=yes
  become: true
  become_method: sudo
  when: ansible_os_family == "Debian"

# Se crea el usuario de postgres kamailio
- name: Create kamailio postgres user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name=kamailio password=kamailiorw role_attr_flags=SUPERUSER

# Se crea el usuario de postgres kamailiorw
- name: Create kamailioro postgres user
  postgresql_user: name=kamailioro password=kamailioro role_attr_flags=SUPERUSER
  become: yes
  become_method: sudo
  become_user: postgres
