# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se cambia la IP en el acrhivo de config del webphone
- name: Creation of config.js file
  template: "src=templates/config.js.j2 dest={{ static_route }}/JS/config.js owner={{ usuario }} group={{ usuario }}"
  tags: ['postinstall','changeip']

# Se borra el cache de javascript, esto solo se hace cuando es postinstall
- name: Erase the javascript cache files (if exists)
  file: path="{{ install_prefix }}static/CACHE/{{ item }}" state=absent
  with_items:
    - js
    - manifest.json
  tags: ['never','postinstall']

# Se corre un compendio de comandos de django con manage.py  https://docs.ansible.com/ansible/2.5/modules/django_manage_module.html#django-manage-module
- name: Run Django migrations and compilemessages
  django_manage: >
          command={{ item }}
          app_path={{ install_prefix }}ominicontacto
          settings=ominicontacto.settings
          virtualenv={{ install_prefix }}virtualenv
  with_items:
          - migrate --noinput
          - populate_history
          - compilemessages
  environment:
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
    PGPASSWORD: "{{ postgres_password }}"
    LANG: en_US.UTF8
  become: true
  become_method: su
  become_user: "{{ usuario }}"
  tags: postinstall

- name: Run collectstatic, compress and regenerar_asterisk commands
  django_manage: command={{ item }} app_path={{ install_prefix }}ominicontacto settings=ominicontacto.settings virtualenv={{ install_prefix }}virtualenv
  with_items:
    - collectstatic
    - collectstatic_js_reverse
    - compress --force
    - regenerar_asterisk
  environment:
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_method: su
  become_user: "{{ usuario }}"
  tags: ['changeip','postinstall']

# Se crea el usuario admin
- name: Create admin superuser
  django_manage: command="createsuperuser --noinput --username={{ admin_user }} --email=admin@example.com" app_path={{ install_prefix }}ominicontacto settings=ominicontacto.settings virtualenv={{ install_prefix }}virtualenv
  environment:
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  register: result
  failed_when: false
  become: yes
  become_method: su
  become_user: "{{ usuario }}"

# Se crea un peque√±o script que utiliza expect para setear automaticamente la password del superusuario
- name: Change password of superuser
  template: "src=templates/bin/changepassword.sh.j2 dest={{ install_prefix }}ominicontacto/changepassword.sh mode=0755"

# Se ejecuta el script (verlo en templates para mas info)
- name: Change password
  shell: "./changepassword.sh chdir={{ install_prefix }}ominicontacto"
  environment:
    DJANGO_SETTINGS_MODULE: "ominicontacto.settings"
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_user: "{{ usuario }}"
  become_method: su

# Se borra ese script del sistema
- name: Erase the script for changing superuser password
  file: path={{ install_prefix }}ominicontacto/changepassword.sh state=absent
