# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se borra el cache de javascript, esto solo se hace cuando es postinstall
- name: Erase the javascript cache files (if exists)
  file: path="{{ install_prefix }}static/CACHE/{{ item }}" state=absent
  with_items:
    - js
    - manifest.json
  tags: ['never','postinstall']

# Este script sirve para hacer comandos de manage.py sin necesidad de activar virualenv primero
- name: Generate manage.sh script
  template: src=templates/bin/manage.sh.j2 dest={{ install_prefix }}bin/manage.sh owner={{ usuario }} group={{ usuario }} mode=755
  tags: postinstall

# Se ejecuta primero las migraciones
- name: Run migrations of database
  command: "{{ install_prefix }}bin/manage.sh migrate --noinput"
  become: true
  become_method: su
  become_user: "{{ usuario }}"
  tags: postinstall

# Se crea el usuario admin
- name: Create admin superuser
  command: "{{ install_prefix }}bin/manage.sh createsuperuser --noinput --username={{ admin_user }} --email=admin@example.com"
  register: result
  #failed_when: false
  failed_when:
      - "'is already taken' not in result.stderr"
      - "'is already taken' not in result.stdout"
      - "result.rc != 0"
  become: true
  become_method: su
  become_user: "{{ usuario }}"

# Se ejecutan los comandos de django que necesita omnileads
- name: Execute django commands
  command: "{{ install_prefix }}bin/manage.sh {{ item }}"
  with_items:
    - adicionar_perfil_supervisor_admin
    - populate_history
    - compilemessages
    - collectstatic --noinput
    - collectstatic_js_reverse
    - compress --force
    - regenerar_asterisk
    - regenerar_tareas_preview
    - actualizar_permisos
  become: true
  become_method: su
  become_user: "{{ usuario }}"
  tags: postinstall

# Se crea un peque√±o script que utiliza expect para setear automaticamente la password del superusuario
- name: Change password of superuser
  template: "src=roles/omniapp_second/templates/bin/changepassword.sh dest={{ install_prefix }}ominicontacto/changepassword.sh mode=0755"
  tags: postinstall

# Se ejecuta el script (verlo en templates para mas info)
- name: Change password
  shell: "source {{ install_prefix}}virtualenv/bin/activate && ./changepassword.sh"
  args:
    chdir: "{{ install_prefix }}ominicontacto"
    executable: /bin/bash
  become: true
  become_user: "{{ usuario }}"
  become_method: su
  tags: postinstall

# Se borra ese script del sistema
- name: Erase the script for changing superuser password
  file: path={{ install_prefix }}ominicontacto/changepassword.sh state=absent
  when: admin_pass != ""
