---
# Estas task contienen una serie de multiples tareas de os que se ejecutan luego de creada la base de datos
# y copiado el codigo al servidor

- include: sshkey_transfer.yml
  tags:
    - omniapp
    - postinstall

- include: django_migrations.yml
  tags:
    - omniapp
    - django-migrations
    - postinstall

- include: omniapp_second.yml
  tags:
    - omniapp
    - nginx


- include: wombat.yml
  tags:
    - omniapp
    - wombat
