---
# Estas task contienen una serie de multiples tareas de os que se ejecutan luego de creada la base de datos
# y copiado el codigo al servidor

- include: sshkey_transfer.yml
  tags: postinstall

- include: django_migrations.yml
  tags: ['postinstall','django']

- include: omniapp_second.yml
  tags: ['nginx','postinstall']


- include: wombat.yml
  tags: wombat
