# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

- include: django_migrations.yml
  tags: [omniapp']

- include: omniapp_second.yml
  tags: ['omniapp']

- include: gluster-client.yml
  tags: ['omniapp']
  when: cluster != 0 and is_docker.stdout != "docker"

- include: roles/prerequisitos/tasks/reboot.yml
  when: cluster != 0 and ansible_os_family == "RedHat"

- name: Wait for the server to finish rebooting
  become: no
  local_action: wait_for host="{{ omniapp_ip }}" delay=15 state=started port={{ ansible_ssh_port }} timeout=600
  tags: reboot
  when: ansible_os_family == "RedHat" and cluster !=0
