---

- name: Get the wombat dialer repository
  shell: "wget -P /etc/yum.repos.d http://yum.loway.ch/loway.repo"
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"

- name: Install wombat dialer
  yum: name=wombat state=present
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: true
  become_method: sudo
- meta: clear_host_errors

- name: Add parameters in server.xml of Catalina
  template: src=templates/server.xml.j2  dest=/usr/local/queuemetrics/tomcat/conf/server.xml
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: true
  become_method: sudo

- name: Add the repository key
  shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886"
  when: ansible_os_family == "Debian"
  #apt_key: keyserver=keyserver.ubuntu.com state=present id=0xC2518248EEA14886

- name: Add wombat dialer repositories
  apt_repository: "repo={{ item }} state=present filename=webupd8team-java update_cache=yes codename=xenial"
  with_items:
          - deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
          - deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
  when: ansible_os_family == "Debian"
            #- name: Update for repositories
            #apt: update_cache=yes cache_valid_time=12

- name: Accept Java8 license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: ansible_os_family == "Debian"

- name: Install oracle8 and tomcat8
  apt: name={{ item }} state=present update_cache=yes
  with_items:
          - oracle-java8-installer
          - tomcat8
          - libmysql-java
  when: ansible_os_family == "Debian"

- name: Get wombat dialer
  get_url: url={{ wombat }} dest=/var/lib/tomcat8/webapps/
  register: destino
  when: ansible_os_family == "Debian"

- name: Unarchive downloaded package
  unarchive: src={{ destino.dest }} dest=/var/lib/tomcat8/webapps remote_src=yes
  register: nombres_tar
  when: ansible_os_family == "Debian"

- name: Erase of the tar
  file: dest={{ nombres_tar.src }} state=absent
  when: ansible_os_family == "Debian"

- action: shell ls /var/lib/tomcat8/webapps/
  register: dirwebapps
  when: ansible_os_family == "Debian"

- command: mv /var/lib/tomcat8/webapps/{{ dirwebapps.stdout_lines[1] }} /var/lib/tomcat8/webapps/wombat
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: Copy of mysql-connector-java.jar
  copy: src=/usr/share/java/mysql-connector-java.jar dest=/var/lib/tomcat8/webapps/wombat/WEB-INF/lib/ remote_src=yes
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: Change JAVA_HOME
  lineinfile: "dest=/etc/default/tomcat8 regexp=\"^#JAVA_HOME=\" line=\"JAVA_HOME=/usr/lib/jvm/java-8-oracle\""
  notify: restart tomcat8
  when: ansible_os_family == "Debian"

- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
  when: ansible_os_family == "Debian"

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
  when: ansible_os_family == "Debian"

- name: Install Mysql
  apt: name=mysql-server state=present
  when: ansible_os_family == "Debian"


