# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---
- name: Instalacion de Omnileads con Asterisk en container
  hosts: omnileads
  vars:
          build_dir: "{{ BUILD_DIR }}"
          rama: "{{ RAMA }}"
  vars_prompt:
        - name: "admin_pass"
          prompt: "Ingrese contraseña del admin de Omnileads (contraseña con números, letras y caracteres especiales) default: OML3.1415"
          private: yes
          default: OML3.1415

        - name: "admin_pass2"
          prompt: "Ingrese nuevamente contraseña del admin de Omnileads"
          private: yes

        - name: "formato_conversion"
          prompt: "Ingrese el formato de conversión de grabaciones (wav o mp3, default wav)"
          default: mp3
          private: no

  pre_tasks:
      - assert:
          that:
            - "'{{ admin_pass }}' | length > 8"
          msg: "La contraseña ingresada es demasiado corta"
      - assert:
          that: "'{{ admin_pass }}' == '{{ admin_pass2 }}'"
          msg: "Las contraseñas no son iguales"
      - assert:
          that: "'{{ formato_conversion }}' == 'wav' or '{{ formato_conversion }}' == 'mp3' "
          msg: "Formato inválido"

  gather_facts: True

  roles:
          - {role: prerequisitos, tags: ['yum']}
          - {role: oml_server, tags: ['virtualenv']}
          - kamailio
          - {role: docker, tags: ['docker']}
          - {role: omniapp_second, tags: ['omniapp']}
          - deploy_supervision
