version: '3.7'
services:
  asterisk:
    entrypoint:
      - /home/run_asterisk.sh
    container_name: oml-asterisk-prodenv
    dns: 8.8.8.8
    environment:
      - AMI_USER=${AMI_USER}
      - AMI_PASSWORD=${AMI_PASSWORD}
      - ASTERISK_LOCATION=${ASTERISK_LOCATION}
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - TZ=${TZ}
    image: freetechsolutions/asterisk:${RELEASE}
    networks:
      - prod_net
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - ./recordings:/var/spool/asterisk/monitor/
      - ./sounds:/var/lib/asterisk/sounds/
      - ast_conf_files:/etc/asterisk/
    working_dir: /etc/asterisk

  dialer:
    command: >
      bash -c "sed -i -- 's/127.0.0.1/${MYSQL_HOST}/g' /usr/local/tomcat/webapps/wombat/WEB-INF/tpf.properties && catalina.sh run"
    container_name: oml-dialer-prodenv
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - MYSQL_PWD=${MYSQL_ROOT_PASS}
    image: freetechsolutions/dialer:${DIALER_VERSION}
    networks:
      - prod_net
    ports:
      - ${WD_EXT_PORT}:8080/tcp
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  kamailio:
    container_name: oml-kamailio-prodenv
    depends_on:
      - redis
      - asterisk
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=${TZ}
    image: freetechsolutions/kamailio:${RELEASE}
    networks:
      - prod_net
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - ./certs/:/etc/kamailio/certs/

  nginx:
    container_name: oml-nginx-prodenv
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=${TZ}
    image: freetechsolutions/nginx:${RELEASE}
    networks:
      - prod_net
    privileged: true
    ports:
     - ${NGINX_EXT_PORT}:443/tcp
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - ./recordings:/var/spool/asterisk/monitor
      - ./certs:/etc/nginx/certs/

  omniapp:
    command:
      - /opt/omnileads/run/run_omniapp.sh
    container_name: oml-omniapp-prodenv
    dns: 8.8.8.8
    environment:
      - AMI_USER=${AMI_USER}
      - AMI_PASSWORD=${AMI_PASSWORD}
      - ASTERISK_HOSTNAME=${ASTERISK_HOSTNAME}
      - ASTERISK_LOCATION=${ASTERISK_LOCATION}
      - CALIFICACION_REAGENDA=${CALIFICACION_REAGENDA}
      - DJANGO_ADMIN_PASS=${DJANGO_PASS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DOCKER_IP=${DOCKER_IP}
      - LOGIN_FAILURE_LIMIT=${LOGIN_FAILURE_LIMIT}
      - MONITORFORMAT=${MONITORFORMAT}
      - NGINX_HOSTNAME=${DOCKER_HOSTNAME}
      - EPHEMERAL_USER_TTL=${ECTTL}
      - EXTERNAL_PORT=${NGINX_EXT_PORT}
      - INSTALL_PREFIX=${INSTALL_PREFIX}
      - KAMAILIO_HOSTNAME=${KAMAILIO_HOSTNAME}
      - KAMAILIO_LOCATION=${KAMAILIO_LOCATION}
      - OMNILEADS_HOSTNAME=${OMNILEADS_HOSTNAME}
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PYTHONPATH=${PYTHONPATH}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - SESSION_COOKIE_AGE=${SCA}
      - TZ=${TZ}
      - WOMBAT_HOSTNAME=${WOMBAT_HOSTNAME}
      - WOMBAT_USER=${WOMBAT_USER}
      - WOMBAT_PASSWORD=${WOMBAT_PASSWORD}
    image: freetechsolutions/omniapp:${RELEASE}
    networks:
      - prod_net
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    user: omnileads
    volumes:
      - ./recordings:/opt/omnileads/grabaciones
      - ast_conf_files:/etc/asterisk/
      - ./sounds:/var/lib/asterisk/sounds/
    working_dir: /opt/omnileads/ominicontacto

  redis:
    container_name: oml-redis-prodenv
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
    image: redis:5-alpine
    networks:
      - prod_net
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - ./redis_data:/data

networks:
  prod_net:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
volumes:
  ast_conf_files: