# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---
# Se excluye postgres de la lista de repositorios sng-base y sng-update (cuando usabamos sangomaOS)
- name: Exclude postgres in list of repositories
  ini_file: "path=/etc/yum.repos.d/Sangoma-Base.repo section={{ item }} option=exclude no_extra_spaces=yes value=postgres* state=present"
  with_items:
      - sng-base
      - sng-updates
  become: true
  become_method: sudo
  when: ansible_os_family == "Sangoma"

# Se excluye postgres de la lista de repositorios base y updates
- name: Exclude postgres in list of repositories
  ini_file: "path=/etc/yum.repos.d/CentOS-Base.repo section={{ item }} option=exclude no_extra_spaces=yes value=postgres* state=present"
  with_items:
      - base
      - updates
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

#  Instalo paquetes de asterisk no se instalan con DOCKER=true
- name: Installation of asterisk packages
  yum: name={{ item }} state=present
  with_items:
      - ncurses-devel
      - ncurses-libs
      - libxml2
      - libxml2-devel
      - sqlite-devel
      - newt-devel
      - net-snmp-devel
      - unixODBC
      - unixODBC-devel
      - libtiff-devel
      - audiofile-devel
      - gtk2-devel
      - subversion
      - sendmail
      - sendmail-cf
      - lame
  become: true
  become_method: sudo
  when: ['DOCKER == "false"','ansible_os_family == "RedHat"']

# Instalo paquetes de kamailio -- FIX ME -- si se puede dockerizar kamailio que no se instale esto si DOCKER=true
- name: Installation of kamailio packages
  yum: name={{ item }} state=present
  with_items:
    - libevent-devel
    - gcc
    - gcc-c++
    - bison
    - bison-devel
    - flex
    - expat
    - expat-devel
    - libuuid
    - libuuid-devel
    - xmlrpc-c-devel
    - lynx
    - pcre
    - pcre-devel
    - libtool-ltdl-devel
    - iptables-devel
    - iptables-services
    - libpcap-devel
    - glib2-devel
    - json-glib-devel
    - redis
    - hiredis
    - hiredis-devel
    - libunistring-devel.x86_64
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

- meta: clear_host_errors

# Se instala el repo de postgresql9.6
- name: Install of postgresql 9.6
  yum: "name={{ postgresql_url }} state=present validate_certs=no "
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

#Se instalan todos los paquetes de postgresql96
- yum: name=postgresql96* state=present
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Se instalan paquetes de App (centos)
- name: Install the app and services packages
  yum: "name={{ item }} state=present"
  with_items:
      - python-psycopg2.x86_64
      - python2-psycogreen.noarch
      - python
      - python-virtualenv
      - python-devel
      - mysql-connector-python
      - mysql-devel
      - nginx
      - nginx-all-modules
      - libjpeg-turbo-devel
      - libffi-devel
      - libffi
      - libpqxx
      - libpqxx-devel
      - cairo-devel
      - pycairo
      - pycairo-devel
      - cairo
      - libpqxx
      - libpqxx-devel
      - python-pycha
      - libxslt-devel
      - libxslt-python
      - libxslt
      - python-lxml
      - libxslt-python
      - postgresql-plpython
      - postgresql-libs
      - postgresql-devel
      - libsass-devel
      - libsass
      - python2-pip.noarch
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"
- meta: clear_host_errors

# Instalar php56wpgsql toca por aca por aparte por un error que me salia hace mucho de postgres
- name: install php56wpgsql
  yum: name=php56w-pgsql state=present
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

- meta: clear_host_errors

# Se a√±aden los binarios que no van a necesitar password al hacerlos con sudo
- name: Edit sudoers to execute binaries withouth password
  lineinfile: "dest=/etc/sudoers line=\"{{ usuario }} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/bin/rsync, /usr/sbin/asterisk\""
  become: yes
  become_method: sudo

# Tareas para hacer el reboot del server y esperar a que vuelva y siga ejecutando tareas. Esto lo saque de un stackoverflow
- name: Reboot the server for kernel update
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: LOCALHOST == "true"

- name: Wait for the server to finish rebooting
  become: no
  local_action: wait_for host="{{ omni_ip }}" delay=15 state=started port={{ ssh_port }} timeout=600
  when: LOCALHOST == "true"
