# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

#----------------------------------------------------------------------
# Directorios básicos
#----------------------------------------------------------------------

# Se crea la llave publica y privada del usuario omnileads #https://docs.ansible.com/ansible/2.5/modules/user_module.html
- name: Create {{ usuario }} user and public key
  user: name={{ usuario }} generate_ssh_key=yes group={{ usuario }} ssh_key_bits=2048 state=present shell=/bin/bash
  become: true
  become_method: sudo
  tags: omniapp

# Creo directorio padre, home del usuario omnileads
- name: Create the ominicontacto directorie
  file: "dest={{ install_prefix }} state=directory owner={{ usuario }} group={{ usuario }} recurse=yes"
  when: desarrollo == 0
  tags: omniapp

# Se crean los directorios basicos
- name: Create other directories
  file: "dest={{ item }} state=directory owner={{ usuario }} group={{ usuario }} mode=0755 recurse=yes"
  with_items:
      # Directorio que contiene configuracion de pip
          - "{{ install_prefix }}.pip"
      # Directorio donde se guarda el archivo de settings de django
          - "{{ install_prefix }}local"
      # Directorio donde se crean los json para hablar con la api de wombat
          - "{{ install_prefix }}wombat-json"
      # Directorio que guarda scripts de bash y de inicio del sericio omnileads
          - "{{ install_prefix }}bin"
      # Directorio donde se guardan los backsup que se hacen
          - "{{ install_prefix }}backup"
      # Donde se guardn los certificados de nginx
          - "{{ install_prefix }}nginx_certs"
      # Donde se guardan los csv de los reportes
          - "{{ install_prefix }}media_root/reporte_campana"
      # Donde se guarda el codigo JS y CSS luego de hace un python manage.py collectstatic
          - "{{ install_prefix }}static"
      # DOnde se guardan los logs uwsgi.log y django.log
          - "{{ install_prefix }}log"
          - "{{ install_prefix }}run"
          - "{{ install_prefix }}asterisk/etc/asterisk"
          - "{{ install_prefix}}virtualenv"
  tags: omniapp

#----------------------------------------------------------------------
# pip / virtualenv
#----------------------------------------------------------------------

# Opcion para agregar al pip
- name: Setup pip
  ini_file: >
    dest={{ install_prefix }}.pip/pip.conf
    section=install
    option='download-cache'
    value='{{ install_prefix }}.pip/cache'

#----------------------------------------------------------------------
# ics_app installed, do this
#----------------------------------------------------------------------

- name: Get the ics_settings settings in temp file
  shell: cat {{ install_prefix }}local/oml_settings_local.py | grep "#ICS" -A200 > /tmp/oml_settings_local.py2
  tags: ['postinstall','changenetwork','changepassword']
  when: ics_exists.rc == 0

# El codigo que está en /var/tmp/ominicontacto_build/ se pasa a /opt/omnileeads/ominicontacto
- name: Upload built (rsync to /ominicontacto)
  synchronize: "src={{ build_dir }}/{{ item }} dest={{ install_prefix }}ominicontacto/ delete=yes checksum=yes times=no"
  with_items:
    - api_app
    - configuracion_telefonia_app
    - manage.py
    - ominicontacto
    - ominicontacto_app
    - ominicontacto_voip
    - Omnisup
    - reciclado_app
    - reportes_app
    - requirements.txt
    - utiles_globales.py
    - test
    - tests
  when: desarrollo == 0
  tags: postinstall

# Se clona el repo si es un entorno de desarrollo
- name: Clone of OML repository (develop server)
  git: repo=https://gitlab.com/omnileads/ominicontacto.git dest={{ install_prefix }}ominicontacto/ accept_hostkey=yes force=yes accept_hostkey=yes version={{ rama }}
  when: desarrollo == 1 and ominicontacto_exists.rc == 1

# Seteo posesion de ominicontacto al usuario omnileads
- name: Change owner and group of ominicontacto
  file: "path={{ install_prefix }}ominicontacto owner={{ usuario }} group={{ usuario }} recurse=yes"

# Se hace el upgrade de python setuptools usando pip. https://docs.ansible.com/ansible/2.5/modules/pip_module.html#pip-module
# El environment sirve para setear variables de entorno necesarias
- name: Upgrade of python setuptools
  pip:
    name=setuptools
    virtualenv={{ install_prefix }}virtualenv
    virtualenv_command=/usr/bin/virtualenv
    extra_args=--upgrade
  environment:
    PATH: "{{ install_prefix }}virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-{{ postgresql_version }}/bin"
    PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_method: su
  become_user: "{{ usuario }}"

# Se instalan los paquetes que hay en el requirements.txt usando pip
- name: Setup virtualenv
  pip:
    requirements={{ install_prefix }}ominicontacto/requirements.txt
    virtualenv={{ install_prefix }}virtualenv
    virtualenv_command=/usr/bin/virtualenv
  environment:
      PATH: "{{ install_prefix }}virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-{{ postgresql_version }}/bin"
      PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_method: su
  become_user: "{{ usuario }}"
- meta: clear_host_errors

##### Entorno de desarrollo

# Instalo los paquetes extras necesarios:
- name: Install extra packages for development (develop server)
  pip:
    name={{ item }}
    virtualenv={{ install_prefix }}virtualenv
    virtualenv_command=/usr/bin/virtualenv
  with_items:
    - django-sslserver==0.20
    - django-debug-toolbar==1.9.1
    - django-extensions==1.9.8
    - django-cors-headers==2.4.0
  environment:
      PATH: "{{ install_prefix }}virtualenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/pgsql-{{ postgresql_version }}/bin"
      PYTHONPATH: '{{ install_prefix }}ominicontacto:{{ install_prefix }}local'
  become: true
  become_method: su
  become_user: "{{ usuario }}"
  when: desarrollo == 1

# Agrego el comando django-server y 1210 para levantar y matar el entorno de omnileadsdesarrollo
- name: Add django-server and kill-django-server scripts (develop server)
  template: src=templates/bin/{{ item }} dest=/usr/bin/{{ item }} mode=755
  with_items:
    - django-server
    - kill-django-server
  when: desarrollo == 1

# Se sube el archivo oml_settings_local.py
- name: Upload oml_settings_local.py
  template: src=templates/oml_settings_local.py.j2 dest={{ install_prefix }}local/oml_settings_local.py
  tags: ['omniapp', 'changenetwork','postinstall','changepassword']

- name: Copy the content of of ics_settings in oml_settings_local
  shell: "cat /tmp/oml_settings_local.py2 >> oml_settings_local.py"
  args:
    chdir: "{{ install_prefix }}/local"
  tags: ['changenetwork','postinstall','changepassword']
  when: ics_exists.rc == 0

# Se hace el link simbolico del archivo oml_settings_local a ominicontacto/, para que se pueda hacer manage.py
- name: Creation of simbolic link of oml_settings_local.py
  file: state=link src={{ install_prefix }}local/oml_settings_local.py dest={{ install_prefix }}ominicontacto/oml_settings_local.py owner={{ usuario }} group={{ usuario }} force=true
  tags: omniapp
