---

- name: Descarga de paquetes de asterisk
  get_url: "url={{ item }} dest=/usr/src/"
  register: destino
  with_items:
        - "{{ dahdi_linux }}"
        - "{{ libpri }}"
        - "{{ asterisk_centos }}"
        - "{{ asterisk_v13 }}"
        - "{{ jansson }}"

- name: Descompresion de todos los paquetes
  unarchive: "src={{ item }} dest=/usr/src/ remote_src=yes"
  with_items:
          - "{{ destino.results[0].dest }}"
          - "{{ destino.results[1].dest }}"
          - "{{ destino.results[2].dest }}"
          - "{{ destino.results[3].dest }}"
          - "{{ destino.results[4].dest }}"
  register: nombres_tar

- name: Borrado de los tar
  file: "dest={{ item }} state=absent"
  with_items:
         - "{{ nombres_tar.results[0].src }}"
         - "{{ nombres_tar.results[1].src }}"
         - "{{ nombres_tar.results[2].src }}"
         - "{{ nombres_tar.results[3].src }}"
         - "{{ nombres_tar.results[4].src }}"

- action: shell ls /usr/src/
  register: dirsrc

- name: Instalacion de Iksemel-Master
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[3] }}"
  with_items:
        - ./autogen.sh
        - ./configure
        - make
        - make install

- name: Instalacion de Dahdi Linux
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[1] }}"
  with_items:
        - "make all"
        - "make install"
        - "make config"

- name: Instalacion de libpri
  shell: "{{ item }} chdir=/usr/src/{{dirsrc.stdout_lines[6] }}"
  with_items:
          - "make"
          - "make install"

- name: Instalacion de jansson
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[4] }}"
  with_items:
          - "autoreconf -i"
          - "./configure --libdir=/usr/lib64"
          - "make"
          - "make install"

- name: Creacion de carpeta /tmp/downloads
  file: path=/tmp/downloads state=directory mode=755

- name: Descarga de pjsip-project
  shell: "wget -O /tmp/downloads/pjproject-2.6.tar.bz2 http://www.pjsip.org/release/2.6/pjproject-2.6.tar.bz2 chdir=/tmp/downloads"
- shell: "wget -O /tmp/downloads/pjproject-2.6.md5 http://www.pjsip.org/release/2.6/MD5SUM.txt chdir=/tmp/downloads"
  register: command_result
  failed_when: "'ERROR 404: Not Found' not in command_result.stderr"
  changed_when: False

- name: Instalacion de asterisk
  shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[0] }}"
  with_items:
          - contrib/scripts/install_prereq install
          - ./configure --libdir=/usr/lib64 --with-externals-cache=/tmp/downloads

- shell: "contrib/scripts/get_mp3_source.sh chdir=/usr/src/{{ dirsrc.stdout_lines[0] }}"
  register: command_result
  failed_when: "'ERROR 404: Not Found' not in command_result.stderr"
  changed_when: False

- shell: "{{ item }} chdir=/usr/src/{{ dirsrc.stdout_lines[0] }}"
  with_items:
          - make menuselect.makeopts
          - menuselect/menuselect --enable format_mp3
          - make
          - make install
          - make config
          - ldconfig
          - chkconfig asterisk off
- meta: clear_host_errors

- name: Set up permissiond and raise up service
  shell: "{{ item }}"
  with_items:
          - "chown asterisk. /var/run/asterisk"
          - "chown -R asterisk. /etc/asterisk"
          - "chown -R asterisk. /var/lib/asterisk"
          - "chown -R asterisk. /var/log/asterisk"
          - "chown -R asterisk. /var/spool/asterisk"
          - "chown -R asterisk. /usr/lib64/asterisk"
          - "chown -R asterisk. /var/www/"

- name: Apache adjustments
  shell: "{{ item }}"
  with_items:
      - sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php.ini
      - sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/httpd/conf/httpd.conf
      - sed -i 's/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf

- lineinfile: "dest=/etc/httpd/conf/httpd.conf regexp=\"^ErrorLog\" line=\"ErrorLog /dev/null\""
  notify: restart httpd



