

version: '3.7'
services:
  asterisk:
    entrypoint:
      - /home/run_asterisk.sh
    container_name: oml-{{ asterisk_fqdn }}-devenv
    depends_on:
      - postgresql
    dns: 8.8.8.8
    environment:
      - ASTERISK_LOCATION=${ASTERISK_LOCATION}
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGUSER=${PGUSER}
      - TZ=${TZ}
    image: freetechsolutions/asterisk:{{ asterisk_version }}
    networks:
      - dev_net
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    #user: asterisk
    volumes:
      - grabaciones:/var/spool/asterisk/monitor/
      - ./asterisk/conf/:/etc/asterisk/
      - ./asterisk/agis/:/var/lib/asterisk/agi-bin/
      - sounds:/var/lib/asterisk/sounds/oml/
      - ./asterisk/odbc.ini:/etc/odbc.ini
      - ./asterisk/odbcinst.ini:/etc/odbcinst.ini
      - ./asterisk/others/:/home/
      - {{ repo_location }}/ominicontacto_voip/asterisk-files/conf/:/var/tmp/
      - ssh_keys_devenv:/opt/sshkeys
    working_dir: /etc/asterisk

  dialer:
    container_name: oml-{{ dialer_fqdn }}-devenv
    depends_on:
      - mariadb
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - MYSQL_PWD=${MYSQL_ROOT_PASS}
    image: freetechsolutions/dialer:${DIALER_VERSION}
    networks:
      dev_net:
        ipv4_address: ${DIALER_IP}
    ports:
      - ${WD_EXT_PORT}:8080/tcp
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

  kamailio:
    container_name: oml-{{ kamailio_fqdn }}-devenv
    depends_on:
      - redis
      - asterisk
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=${TZ}
    image: {{ kamailio_image }}
    networks:
      dev_net:
        ipv4_address: {{ kamailio_ip }}
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - {{ repo_location }}/ominicontacto_voip/kamailio-files:/etc/kamailio
      - ./certs/:/etc/kamailio/certs/

  mariadb:
    container_name: oml-{{ mariadb_fqdn }}-devenv
    dns: 8.8.8.8
    environment:
      - TZ={{ TZ }}
      - MARIADB_ROOT_PASSWORD={{ mysql_root_password }}
      - MARIADB_DATABASE=wombat
      - MARIADB_USER=wombat
      - MARIADB_PASSWORD=dials
    image: {{ mariadb_image }}
    networks:
      - dev_net
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - mariadb_data:/bitnami

  nginx:
    container_name: oml-{{ nginx_fqdn }}-devenv
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ={{ TZ }}
    image: {{ nginx_image }}
    networks:
      - dev_net
    privileged: true
    ports:
     - "{{ nginx_external_port }}:443/tcp"
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - ./certs:/etc/nginx/certs/
      - ./nginx/:/etc/nginx/
      - grabaciones:/var/spool/asterisk/monitor/

  omniapp:
    command:
      - {{ install_prefix }}run/run_omniapp.sh
    container_name: oml-{{ omniapp_fqdn }}-devenv
    dns: 8.8.8.8
    environment:
      - AMI_USER=${AMI_USER}
      - AMI_PASSWORD=${AMI_PASSWORD}
      - ASTERISK_HOSTNAME=${ASTERISK_HOSTNAME}
      - ASTERISK_LOCATION=${ASTERISK_LOCATION}
      - CALIFICACION_REAGENDA=${CALIFICACION_REAGENDA}
      - DIALER_IP=${DIALER_IP}
      - DJANGO_ADMIN_PASS=${DJANGO_PASS}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - NGINX_HOSTNAME=${DOCKER_HOSTNAME}
      - EPHEMERAL_USER_TTL=${ECTTL}
      - EXTERNAL_PORT=${NGINX_EXT_PORT}
      - INSTALL_PREFIX=${INSTALL_PREFIX}
      - KAMAILIO_IP=${KAMAILIO_IP}
      - KAMAILIO_HOSTNAME=${KAMAILIO_HOSTNAME}
      - KAMAILIO_LOCATION=${KAMAILIO_LOCATION}
      - OMNILEADS_IP=${OMNILEADS_IP}
      - OMNILEADS_HOSTNAME=${OMNILEADS_HOSTNAME}
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PYTHONPATH=${PYTHONPATH}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - RTPENGINE_HOSTNAME=${RTPENGINE_HOSTNAME}
      - SESSION_COOKIE_AGE=${SCA}
      - TZ=${TZ}
      - WOMBAT_HOSTNAME=${WOMBAT_HOSTNAME}
      - WOMBAT_USER=${WOMBAT_USER}
      - WOMBAT_PASSWORD=${WOMBAT_PASSWORD}
    image: freetechsolutions/omniapp:${DEVENV_VERSION}
    networks:
      dev_net:
        ipv4_address: ${OMNILEADS_IP}
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true
    user: omnileads
    volumes:
      - {{ repo_location }}:{{ install_prefix }}ominicontacto/
      - ssh_keys_devenv:{{ install_prefix }}.ssh/
      - ./omniapp/:{{ install_prefix }}run/
      - ./omniapp/conversor.sh:{{ install_prefix }}bin/conversor.sh
      - ./omniapp/omni-asterisk-logout.py:{{ install_prefix }}bin/omni-asterisk-logout.py
      - grabaciones:{{ install_prefix }}grabaciones
      - sounds:/var/lib/asterisk/sounds/
    working_dir: {{ install_prefix}}ominicontacto

  postgresql:
    container_name: oml-{{ postgresql_fqdn }}-devenv
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    image: freetechsolutions/postgresql:${POSTGRES_VERSION}
    networks:
      - dev_net
    ports:
      - ${PG_EXT_PORT}:5432/tcp
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  pbx-emulator:
    container_name: pbx-emulator
    hostname: pbx-emulator
    dns: 8.8.8.8
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=${TZ}
    image: freetechsolutions/pbx-emulator:${PBXEMULATOR_VERSION}
    networks:
      - dev_net
    ports:
      - 5060:5060/udp
      - 10000-10020:10000-10020/udp
    privileged: true
    restart: on-failure
    stdin_open: true
    stop_grace_period: 1m30s
    tty: true

  redis:
    container_name: oml-{{ redis_fqdn }}-devenv
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
    networks:
      - dev_net
    image: {{ redis_image }}
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s
    volumes:
      - redis_data:/data
  rtpengine:
    container_name: oml-{{ rtpengine_fqdn }}-devenv
    dns: 8.8.8.8
    environment:
      - TZ=${TZ}
    image: freetechsolutions/rtpengine:${RTPENGINE_VERSION}
    networks:
      - dev_net
    privileged: true
    restart: on-failure
    stop_grace_period: 1m30s

networks:
  dev_net:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET}"

volumes:
  grabaciones:
  mariadb_data:
  postgresql_data:
  redis_data:
  sounds:
  ssh_keys_devenv:
