---

# Docker hosts general variable

# Images used
asterisk_image: debian:buster-slim
base_image: alpine:3.9
dialer_image: tomcat:8.5-alpine
kamailio_image: kamailio/kamailio-ci:5.2
mariadb_image: bitnami/mariadb:latest
nginx_image: nginx:mainline-alpine
postgres_image: postgres:{{ postgresql_version }}
rtpengine_image: ubuntu:18.04
redis_image: redis:5-alpine
# Images for EFK
elasticsearch_image: elasticsearch:7.1.0
fluentd_image: qqbuby/fluentd:v1.2-es
kibana_image: kibana:7.1.0

# Settings of folder structure
usuario: "{{ docker_user }}"
efk_location: "{{ deploy_location }}/efk"
odbc_location: "{{ ast_local_location }}"

# Docker hub credentials to push images
docker_login_user:
docker_login_email:
docker_login_pass:

asterisk_fqdn: asterisk
dialer_fqdn: dialer
kamailio_fqdn: kamailio
mariadb_fqdn: mariadb
nginx_fqdn: nginx
omniapp_fqdn: omniapp
postgresql_fqdn: postgresql
redis_fqdn: redis
rtpengine_fqdn: rtpengine
database_fqdn: "{{ postgresql_fqdn }}"
