---

- name: Print omni_distribution
# nos aseguramos q' "omni_distribution" est√© dentro de los SO permitidos.
# si no es asi, esta task generara un error
  debug: msg="omni_distribution es {{ ansible_os_family }}"

- name: Check omni_distribution
  fail: msg="omni_distribution con valor {{ ansible_os_family }} es invalida"
  when: (
      ansible_os_family != "RedHat" and
      ansible_os_family != "Sangoma" and
      ansible_os_family != "Debian"
      )

- name: Check if Asterisk is installed in /etc
  command: test -d /etc/asterisk
  ignore_errors: true
  register: asterisk_etc_installed
  tags: postinstall
  become: true
  become_method: sudo

- set_fact: asterisk_location={{ install_prefix }}asterisk
  when: asterisk_etc_installed|failed
  tags: postinstall

- set_fact: asterisk_location=
  when: asterisk_etc_installed|succeeded
  tags: postinstall

- name: Creation of {{ usuario }} group
  group: name={{ usuario }} state=present
  become: true
  become_method: sudo

- include: centos_prerequisitos.yml
  when: ansible_os_family == "RedHat"

- include: installations.yml

- include: setup_mariadb.yml
  when: ansible_os_family == "RedHat"

- include: postgres-installation.yml
