---

- include: sshkey_transfer.yml
  tags:
    - omniapp
    - sshkey-transfer

- include: django_migrations.yml
  tags:
    - omniapp
    - django-migrations
    - postinstall

- include: queuelog_trigger.yml
  tags:
    - omniapp
    - queuelog-trigger
    - postinstall

- include: omniapp_second.yml
  tags:
    - omniapp
    - nginx


- include: wombat.yml
  tags:
    - omniapp
    - wombat