---

- name: Upload nginx.conf configuration
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: true
  become_method: sudo

- name: Enable nginx
  shell: systemctl enable nginx
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"
  become: true
  become_method: sudo

#- name: Copy of the ominicontacto nginx configuration
#  copy: "src={{ install_prefix }}ominicontacto/nginx/ominicontacto-twohosts.conf dest=/etc/nginx/conf.d/ remote_src=yes"
#  when: ansible_os_family == "Debian"
#- shell: "mv /etc/nginx/conf.d/ominicontacto-twohosts.conf /etc/nginx/conf.d/ominicontacto.conf"
#  when: ansible_os_family == "Debian"

#- name: Copy of the ominicontacto nginx configuration
#  copy: "src={{ install_prefix }}ominicontacto/nginx/ominicontacto-onehost.conf dest=/etc/nginx/conf.d/ remote_src=yes"
#  when: ansible_os_family == "RedHat" or ansible_os_family == "Sangoma"
#- shell: "mv /etc/nginx/conf.d/ominicontacto-onehost.conf /etc/nginx/conf.d/ominicontacto.conf"
#  when: ansible_os_family == "RedHat" or ansible_os_family == "Sangoma"

- name: Create of ominicontacto.conf
  template: src=templates/ominicontacto.conf.j2 dest=/etc/nginx/conf.d/ominicontacto.conf
  become: true
  become_method: sudo

- name: Copy of the certificates in nginx
  copy: "src={{ install_prefix }}kamailio/etc/certs/{{ item }} dest={{ install_prefix }}nginx_certs/ remote_src=yes"
  with_items:
      - cert.pem
      - key.pem
  become: true
  ignore_errors: yes
  become_method: sudo
  tags: kamailio-cert
  notify: restart nginx

- name: Create of oml_uwgsi.ini script
  template: src=templates/oml_uwsgi.ini.j2 dest={{ install_prefix }}bin/oml_uwsgi.ini mode=755 owner={{ usuario }} group={{ usuario }}

- name: Create ominicontacto-daemon service
  template: src=templates/ominicontacto-daemon.j2 dest=/etc/init.d/ominicontacto-daemon mode=755 owner=root group=root
  become: true
  become_method: sudo

- name: Start the ominicontacto-daemon service
  command: "{{ item }}"
  with_items:
          - yum install '/lib/lsb/init-functions' -y
          - "service ominicontacto-daemon start"
          - "service ominicontacto-daemon stop"
          - "chkconfig ominicontacto-daemon on"
          - "service ominicontacto-daemon start"
  become: true
  become_method: sudo
  ignore_errors: yes
  when: ansible_os_family == "Sangoma" or ansible_os_family == "RedHat"

- name: Create the ominicontacto-daemon service
  shell: "{{ item }}"
  with_items:
          - "update-rc.d ominicontacto-daemon defaults"
          - "update-rc.d ominicontacto-daemon enable 2"
          - "update-rc.d ominicontacto-daemon enable 3"
          - "update-rc.d ominicontacto-daemon enable 4"
          - "update-rc.d ominicontacto-daemon enable 5"
          - "service ominicontacto-daemon start"
  become: true
  become_method: sudo
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: Copy of the Kamailio cert in voip.cert
  template: src=templates/concatenate.sh dest={{ install_prefix }}bin/concatenate.sh mode=755
  ignore_errors: yes
  tags: kamailio-cert
  become: true
  become_method: sudo

- shell: "bash concatenate.sh chdir={{ install_prefix }}bin"
  tags: kamailio-cert
  ignore_errors: yes
  become: true
  become_method: sudo

- name: Generate changeip.sh script
  template: src=templates/changeip.sh.j2 dest={{ install_prefix }}bin/changeip.sh owner={{ usuario }} group={{ usuario }} mode=755

- name: Generate manage.sh script
  template: src=templates/manage.sh.j2 dest={{ install_prefix }}bin/manage.sh owner={{ usuario }} group={{ usuario }} mode=755
