---

- name: Disable Selinux
  command: "{{ item }}"
  with_items:
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/sysconfig/selinux
      - sed -i 's/\(^SELINUX=\).*/\SELINUX=disabled/' /etc/selinux/config
  become: true
  become_method: sudo
  tags: issabel

- name: Update/upgrade of centos
  yum: name='*' state=latest update_cache=yes
  become: true
  become_method: sudo
  tags: issabel

- name: Install Development tools
  command: "yum -y groupinstall core base \"Development Tools\""
  become: true
  become_method: sudo
  tags: issabel

- name: Install of dependencies
  yum: name={{ item }} state=present
  with_items:
       - lynx
       - tftp-server
       - unixODBC
       - mariadb-server
       - mariadb
       - httpd
       - ncurses-devel
       - sendmail
       - sendmail-cf
       - sox
       - newt-devel
       - libxml2-devel
       - libtiff-devel
       - audiofile-devel
       - gtk2-devel
       - subversion
       - kernel-devel
       - git
       - crontabs
       - cronie
       - cronie-anacron
       - wget
       - vim
       - uuid-devel
       - sqlite-devel
       - net-tools
       - gnutls-devel
       - python-devel
       - texinfo
  become: true
  become_method: sudo
  tags: issabel

- name: Download of epel-release repo
  command: "{{ item }}"
  with_items:
      - rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  register: command_result
  failed_when:
    - "'transferencia fallida' in command_result.stderr"
    - "'failed' in command_result.stderr"
  tags: issabel
  become: true
  become_method: sudo
- meta: clear_host_errors

- name: Download of webtatic repo
  get_url: url=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm dest=/root/ validate_certs=no
  become: true
  become_method: sudo

- name: Installation of webtatic repo
  shell: "rpm -Uvh webtatic-release.rpm chdir=/root"
  register: command_result
  become: true
  become_method: sudo
  failed_when:
    - "'ya est√° instalado' not in command_result.stderr"
    - "'already installed' not in command_result.stderr"
    - "command_result.rc != 0"

- name: Install of php56
  yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-pdo
      - php56w-mysql
      - php56w-mbstring
      - php56w-pear
      - php56w-process
      - php56w-xml
      - php56w-opcache
      - php56w-ldap
      - php56w-intl
      - php56w-soap
  become: true
  become_method: sudo
- meta: clear_host_errors

- name: Install of php
  yum: name={{ item }} state=present
  with_items:
      - php
      - php-pdo
      - php-mysql
      - php-mbstring
      - php-pear
      - php-process
      - php-xml
      - php-opcache
      - php-ldap
      - php-intl
      - php-soap
  become: true
  become_method: sudo
- meta: clear_host_errors
  tags: issabel

- name: Download NodeJS setup script
  shell: "curl -sL https://rpm.nodesource.com/setup_8.x | bash -"
  become: true
  become_method: sudo

- name: Install NodeJS
  yum: name=nodejs state=present
  become: true
  become_method: sudo
  tags: issabel

- name: Install Console_Getopt
  pear: name=Console_Getopt state=present
  become: true
  become_method: sudo
- meta: clear_host_errors
  tags: issabel

